config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'pages#home'
 get 'about', to: 'pages#about'
 
 resources :articles
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article <ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum: 100}
    validates :description, presence: true, length: {minimum:20, maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy
    ]
    
    def show
      
    end
    
    def index
        @articles = Article.all
        
    end
    
    def new
        @article = Article.new
      
    end
    
    def edit
      
        
    end 
    def create
      @article = Article.new(article_params)
        if  @article.save
            flash[:notice] = "Article was created and published successfully"
             redirect_to @article
            
        else 
            render 'new'
        end
        
    end 
    
    def update 
        
       if  @article.update(article_params)
            flash[:notice] = "Updated article successfully"
            redirect_to @article
       else
          render 'edit' 
       end
       
    end
      def destroy
         
            @article.destroy
            redirect_to articles_path
      end
            
           #flash[:alert] = "Deleted an article successfully"
           
    private
    
    def set_article
        
      @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description)
    end
    
          
         
           
        
   

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
    def home
    
    end
    
    def about
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors occured while saving the article:</h2>
   <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li>  <%= msg %></li>
    
     <% end %>
   </ul>
   

<% end %>



    <%= form_with(model: @article, local: true ) do |f| %>

    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
    
    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>

  <% end %>

app/views/articles/edit.html.erb
<h1> Edit an article</h1>

<%= render 'form' %>
  
  <%= link_to 'Cancel and Return to Articles Page', articles_path %>

app/views/articles/index.html.erb
<div id= "page-content">
    <h1 class= "text-center mt-4">Listing all Articles </h1>
    <div class= "container">
    
     <% @articles.each do |article|  %>
     <div class= "row justify-content-md-center" >
         <div class= "col-8 mt-4" >
    
          <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            Written By  Ernest Offor Ugwoke
          </div>
          <div class="card-body">
            <h5 class="card-title"> <%= link_to article.title, article_path(article), class:"text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length:50) %> </p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>
                Createted <%= time_ago_in_words(article.created_at) %>  ago 
                Edited <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
     </div>
    </div>
    <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>
  
  
  <%= link_to 'Return to Articles Page', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article's details</h1>

<p> <strong>Title: </strong> <%= @article.title %> </p>
<p> <strong>Description: </strong> <%= @article.description %> </p>

<%= link_to 'Edit', new_article_path(@article) %>  |

<%= link_to 'Delete', article_path(@article),  method: :delete, data: {confirm: "Are you sure you want to delete this article?"} %> | 

<%= link_to 'Return to Article Page', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|  %>
      <%= msg %>
    <% end %>
    <%= yield %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id: "logo"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       

        <%= link_to "Articles" , articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
     
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <%= render 'layouts/messages' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Home', root_path %> |

<%= link_to 'Go to articles Page', articles_path %> 

app/views/pages/home.html.erb
<h1 class= "home1">Welcome to the Homepage</h1>
<div id="page-content">
    
    <div class = "container" id= "home-container">
     <div class="jumbotron text-white text-center">
      <h1 class="display-4">ALPHA BLOG!</h1>
      
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Sign Up</a>
    </div>
</div>
    
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "ernest offor", "https://gitlab.com/offor20", class:"text-white"  %></small>
    </div>
</footer>